test:
  steps: 4  # minimum 1
  mode: test  # run with synthetic data

eval:
  steps: 4
  mode: eval  # run with real data

new_variables:
  steps: 4
  mode: eval
  extra_variables:
    2m_dewpoint_temperature:
      kind: surf
      key: d2m
